server:
  port: 8080


spring:
  main:
    banner-mode: off
  application:
    name: MokuLib
  profiles:
    active: local


mokulib:
  image-path:
    avatars:
      path-mode: absolute
      save-path: F:/moku/avatars/
      visit-path: avatars
    books:
      path-mode: absolute
      save-path: F:/moku/books/
      visit-path: books


logging:
  level:
    pers.liaohaolong.mokulibserver: DEBUG