server:
  port: 8080


spring:
  main:
    banner-mode: off
  application:
    name: MokuLib
  jackson:
    property-naming-strategy: SNAKE_CASE
  profiles:
    active: local


mokulib:
  image:
    avatars:
      visit-path: avatars
      path-mode: absolute
      save-path: F:/moku/avatars/
      save-format: png
    books:
      visit-path: books
      path-mode: absolute
      save-path: F:/moku/books/
      save-format: jpg


logging:
  level:
    pers.liaohaolong.mokulibserver: DEBUG